version: "3"
services:
  postgresDB:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_USER: root
      POSTGRES_DB: meraki
    ports:
      - 5433:5432

  postgresDB:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ozzy
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
